[package]
name = "poseidon-rs"
version = "0.0.8"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Poseidon hash implementation"
repository = "https://github.com/arnaucube/poseidon-rs"
readme = "README.md"

[dependencies]
ff = { package = "ff_ce", git = "https://github.com/Fluidex/ff.git", branch = "serde", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_poseidon_hash"
harness = false

[features]
with-serde = ["serde", "ff/with-serde"]